# @package _global_
SCENARIO_NAME: "Tianjin_zhijingdao"
JUNCTION_NAME: "INT1"
NUM_SECONDS: 600
TRAINING_NUM_SECONDS: 750 # 训练 RL 需要的时间
PHASE_NUMBER: 4
MOVEMENT_NUMBER: 12
CENTER_COORDINATES: [1732, 1170, 100]
SENSOR_INDEX_2_PHASE_INDEX: # 传感器图片 id 和 phase id 对应关系
  0: 2
  1: 3
  2: 1
  3: 0