# @package _global_
SCENARIO_NAME: "SouthKorea_Songdo"
JUNCTION_NAME: "J2"
NUM_SECONDS: 600
PHASE_NUMBER: 4
MOVEMENT_NUMBER: 12
CENTER_COORDINATES: [900, 1641, 100]
SENSOR_INDEX_2_PHASE_INDEX: # 传感器图片 id 和 phase id 对应关系
  0: 2
  1: 3
  2: 1
  3: 0