# @package _global_
SCENARIO_NAME: "India_Delhi"
JUNCTION_NAME: "249783302"
NUM_SECONDS: 1500
TRAINING_NUM_SECONDS: 2000 # 训练 RL 需要的时间
PHASE_NUMBER: 2
MOVEMENT_NUMBER: 4
CENTER_COORDINATES: [19324, 7654, 150]
SENSOR_INDEX_2_PHASE_INDEX: # 传感器图片 id 和 phase id 对应关系
  0: 2
  1: 3
  2: 1
  3: 0